<?php
$doc = new DOMDocument('1.0', 'UTF-8');
$doc->formatOutput = false;
$doc->preserveWhiteSpace = false;
$root_element = $doc->createElement("response");
$doc->appendChild($root_element);

$statusElement = $doc->createElement("success");
$statusElement->appendChild($doc->createTextNode($this->success));
$root_element->appendChild($statusElement);

$versionElement = $doc->createElement("version");
$versionElement->appendChild($doc->createTextNode($this->version));
$root_element->appendChild($versionElement);

header('Content-Type: application/xml');
#Zend_Debug::dump($doc);
print $doc->saveXml();