<script src="/js/bsection.js"></script>

<nav id ="searchStudent">
	<div id="container">
	<form>
		<a style="float:left" href="/index">(Return)</a>
		<a class="pull-right btn btn-success" 
			href="/bsection/add">
		<i class="icon-plus"></i></a>
	</form action ="/bsection" method ="POST">
		<table class="table table-bordered table-condensed table-striped">
			
			<tr>
				<th>Block Section ID</th>
				<th>Block Section</th>
				<th>Semester Number</th>				
				<th>Number Of Subject</th>				
				<th>Details</th>
				<th>edit </th>
				<th>delete</th>
			</tr>
				<?php foreach ($this->bSection as $details):?>
			<tr>
				<td align="center"><?php echo $details['bsection_id']; ?></td>
				<td align="center"><?php echo $details['bsection']; ?></td>
				<td align="center"><?php echo $details['semester_number']; ?></td>
				<td align="center"><?php echo $details['total']; ?></td>
				<td style="width: 1px; wrap: nowrap;">	
				<input type="hidden" name="bSectionID" value="<?php echo $details['bsection_id']; ?>" />

					<a  
						onclick="bSectionID(<?php echo $details['bsection_id']; ?>);viewBSectionDetails(<?php echo $details['bsection_id']; ?>);totalUnits(<?php echo $details['bsection_id']; ?>);"
						id = "blockSectionID" 
						class="btn" 
						title="View Block Section"
						data-toggle="modal" data-target="#bSection-details"> 
							<i class="icon icon-search"></i>
					</a>
				</td>	
				<td style="width: 1px; wrap: nowrap;">	
					<a 
						href="/bsection/edit?bSectionID=<?php echo $details['bsection_id']; ?>" 
				   		class="btn" 
				   		title="edit blocksection"> 
				   			<i class="icon icon-edit"></i>	
					</a>
				</td>					
				<td style="width: 1px; wrap: nowrap;">			
					<a 
						href='/bsection/delete?bSection=<?php echo $details['bsection']; ?>&semesterNumber=<?php echo $details['semester_number']; ?>' 
						class="btn btn-danger" title="blocksection"> 
							<i class="icon icon-remove"></i>
					</a>
				</td>	

			</tr>
			<?php endforeach;?>
		</table>	
	</div>
</nav>

<div id="bSection-details" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" >
        <h4 class="modal-title "  >Block Section Details</h4>
      </div>
    <div class="modal-body">
		<div class = "blocksection">
			
		 </div>
		   <dl>
		        	<dt>totalUnits</dt><dd id="totalUnits"></dd>
		        </dl>
		        <label> list of subject you one to add</label>
			<select class="listsubject" name="getSubjectID" multiple = "multiple" onclick="checkSubjectName();">		
				
			</select>	
		        <label>Subject That will Be Added</label>
			<div class = "addSubjectsTable">
		<table id = "addTableData" class="table table-bordered table-condensed table-striped">

			<tr>
				<th>Block Section ID</th>
				<th>Subjects</th>
			</tr>

		</table>
			</div>

	 </div>	
      <div class="modal-footer">
       	<button data-dismiss="modal" class="btn btn-default" id="button_save" type="submit" name="edit" value="save" onclick="addSubjects()">save</button>
		<button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="icon icon-remove"></i></button>
      </div>
    </div>

  </div>
</div>
