
<script src="/js/admin.js"></script>

<nav id ="searchStudent">
	<div id="container">
	<form>
		<a style="float:left" href="/index">(Return)</a>
		<a class="pull-right btn btn-success" 
			href="/bsection/add">
		<i class="icon-plus"></i></a>
	</form>
		<table class="table table-bordered table-condensed table-striped">
			
			<tr>
				<th>Block Section ID</th>
				<th>Block Section</th>
				<th>Semester Number</th>
				<th>edit </th>
				<th>delete</th>
			</tr>
				<?php foreach ($this->bSection as $details):?>
				<tr>
				<td align="center"><?php echo $details['bsection_id']; ?></td>
				<td align="center"><?php echo $details['bsection']; ?></td>
				<td align="center"><?php echo $details['semester_number']; ?></td>
				<td style="width: 1px; wrap: nowrap;">
					<a href="/bsection/edit?bSectionID=<?php echo $details['bsection_id']; ?>" 
				   		class="btn" 
				   		title="edit blocksection"> 
				   		<i class="icon icon-edit"></i>
					</a>
				</td>					
				<td style="width: 1px; wrap: nowrap;">			
					<a href='/bsection/delete?bSection=<?php echo $details['bsection']; ?>&semesterNumber=<?php echo $details['semester_number']; ?>' 
						class="btn btn-danger" title="blocksection"> 
						<i class="icon icon-remove"></i>
					</a>
				</td>	

			</tr>
			<?php endforeach;?>
		</table>	
	</div>
