
<script src="/js/admin.js"></script>

<nav id ="searchStudent">
	<div id="container">
	<form>
		<a style="float:left" href="/index">(Return)</a>
		<a class="pull-right btn btn-success" 
			href="/blocksection/add">
		<i class="icon-plus"></i></a>
	</form>
		<table class="table table-bordered table-condensed table-striped">
			
			<tr>
				<th>Block Section ID</th>
				<th>Block Section</th>
				<th>Semester Number</th>
			</tr>
				<?php foreach ($this->bSection as $details):?>
				<tr>
				<td align="center"><?php echo $details['bsection_id']; ?></td>
				<td align="center"><?php echo $details['bsection']; ?></td>
				<td align="center"><?php echo $details['semester_number']; ?></td>
				<td>	
			</tr>
			<?php endforeach;?>
		</table>	
	</div>
