<h1>TEST</h1>
<iframe src="<?php echo $this->url; ?>" width="200px"></iframe>

<div class="fb-follow" data-href="https://www.facebook.com/zuck" data-width="200px" data-layout="standard" data-size="large" data-show-faces="true"></div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1729933903964760";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>