<link type="text/css" rel="stylesheet" href="../../../../css/signup.css" />


<form action="/signup/index" Method="POST">
      <?php if (!empty($this->students['error'])): ?>
        <div>
          <?php echo $this->students['error']; ?>
        
        </div>
      <?php endif; ?> 
  <div class="container">
    <label><b>Email</b></label>
    <input type="email" placeholder="Enter Email" name="email" required autofocus>
  
    <label><b>Name</b></label>
    <input type="text" placeholder="Enter Name" name="name" required autofocus>
  
    <label><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last Name" name="lastname" required autofocus>


    <label><b>User</b></label>
    <input type="text" placeholder="Enter User" pattern=".{8,12}" required title="8 to 12 characters" name="user" required autofocus>

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" pattern=".{8,12}" required title="8 to 12 characters" name="psw" required autofocus>

    <label><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" pattern=".{8,12}" required title="8 to 12 characters" name="psw-repeat" required autofocus>
    <input type="checkbox" checked="checked"> Remember me

    <div class="clearfix">
      <button type="button"  class="cancelbtn"><a href="/login/" >Cancel</a> </button>
      <button type="submit" class="signupbtn" name="save">Sign Up</button>
    </div>
  </div>
</form>x