<script src="/js/semester.js"></script>
<nav id ="searchStudent">
	<div id="container">
	<form>
		<a style="float:left" href="/">(Return)</a>
	</form>
		<table class="table table-bordered table-condensed table-striped">
			<a class="pull-right btn btn-success" 
					href="/Semester/add">
					<i class="icon-plus"></i></a>
			<tr>
				<th>Semester ID</th>
				<th>Date Start</th>
				<th>Date End</th>
				<th>Details</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>

			<?php foreach ($this->semesters as $details):?>
				<tr>
				<td align="center"><?php echo $details['semester_id']; ?></td>
				<td align="center"><?php echo $details['date_start']; ?></td>
				<td align="center"><?php echo $details['date_end']; ?></td>
				<td>
					<a 
						onclick="viewDetails(<?php echo $details['semester_id']; ?>);" 
						class="btn" 
						title="edit Student"
						data-toggle="modal" data-target="#semester-details"
						> 
						<i class="icon icon-search"></i>
					</a>	

				<td> <a href="/semester/edit?semester_id=<?php echo $details['semester_id']; ?>" 
							class="btn" title="edit Student"> 
							<i class="icon icon-edit"></i>
					</a>

				</td>
				<td>
					<a id="href_delete" href='/semester/delete?semester_id=<?php echo $details['semester_id']; ?>' 
					class="btn btn-danger" title="Delete Student"> 
						<i class="icon icon-remove"></i>
					</a>
				</td>
				</tr>
			<?php endforeach;?>
		</table>	
	
	</div>
<div id="semester-details" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Semester Details</h4>
      </div>
      <div class="modal-body">
        <dl>
        	<dt>semesterID</dt><dd id="semesterID"></dd>
        	<dt>Semester date Start</dt><dd id="semesterDateStart"></dd>
        	<dt>Semester Date End</dt><dd id="semesterDateEnd"></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal"><i class="icon icon-remove"></i></button>
      </div>
    </div>

  </div>
</div>

</nav>


