
<script src="/js/admin.js"></script>

<nav id ="searchStudent">
	<div id="container">
	<form>
		<a style="float:left" href="/index">(Return)</a>
		<a class="pull-right btn btn-success" 
			href="/bsectionsubject/add">
		<i class="icon-plus"></i></a>
	</form>
		<h1><?php echo $this->bSection ?> <?php echo $this->semesterNumber ?></h1>
		<table class="table table-bordered table-condensed table-striped">
			
			<tr>
				<th>Subject</th>
				<th>Lec Unit</th>
				<th>Lab Unit</th>
				<th>Subject Unit</th>
				<th>edit </th>
				<th>delete</th>
			</tr>
				<?php foreach ($this->BsectionSubject as $details):?>
				<tr>
				<td align="center"><?php echo $details['subject']; ?></td>
				<td align="center"><?php echo $details['lec_unit']; ?></td>
				<td align="center"><?php echo $details['lab_unit']; ?></td>
				<td align="center"><?php echo $details['subject_unit']; ?></td>
				<td style="width: 1px; wrap: nowrap;">
					<a href="/bsectionsubject/edit?bSectionID=<?php echo $details['bsection_id']; ?>" 
				   		class="btn" 
				   		title="edit blocksection"> 
				   		<i class="icon icon-edit"></i>
					</a>
				</td>					
				<td style="width: 1px; wrap: nowrap;">			
					<a href='/bsectionsubject/delete?bSection=<?php echo $details['bsection']; ?>&semesterNumber=<?php echo $details['semester_number']; ?>' 
						class="btn btn-danger" title="blocksection"> 
						<i class="icon icon-remove"></i>
					</a>
				</td>	

			</tr>
			<?php endforeach;?>
		</table>	
	</div>
