<?php echo $this->doctype() ?>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="../../../css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="../../../css/mystyles.css" />
    <script src="/js/vendor/jquery-3.1.1.min.js"></script>
    <script src="/js/vendor/bootstrap.min.js"></script>
</head>

<body>
  <?php echo $this->layout()->content ?>
</body>
</html>