
    <script src="/js/students.js"></script>

	<nav id ="searchStudent">
		<div id="container">
			<div class="navbar">
				<div class="navbar-inner">
						<h1>Students Records</h1>
					<form class="navbar-form pull-right">
					  	<a type="button" class="btn" href="/index">return</a>
					</form>
				</div>
			</div>
			<form>
				<a style="float:left"  href="/logic/studentPaginated.php">(paginated)</a>
				<a class="pull-right btn btn-success" href="/students/add">
					<i class="icon-plus"></i>
				</a>
			</form>

			<?php if (empty($this->students)): ?>
				<div class="alert alert-info">No students yet</div>
			<?php else: ?>
				<table class="table table-bordered table-condensed table-striped"> 
					<p id="delete"></p>
					<tr>
						<th>ID</th>
						<th>FirstName</th>
						<th>LastName</th>
						<th>Status</th>
						<th>Actions</th>
					</tr>
					<?php foreach ($this->students as $details): ?>
						<tr>
						<td align="center"><?php echo $details['student_id']; ?></td>
						<td align="center"><?php echo $details['first_name']; ?></td>
						<td	align="center"><?php echo $details['last_name']; ?></td>
						<td align="center"><?php echo $details['payed']; ?></td>
						<td style="width: 1px; white-space: nowrap;" nowrap>
							<a 
								onclick="viewDetails(<?php echo $details['student_id']; ?>);" 
								class="btn" 
								title="edit Student"
								data-toggle="modal" data-target="#student-details"
								> 
								<i class="icon icon-search"></i>
							</a>	

							<a href="/students/edit?student_id=<?php echo $details['student_id']; ?>" class="btn" title="edit Student"> 
								<i class="icon icon-edit"></i>
							</a>

							<a id="href_delete" href='/students/delete?student_id=<?php echo $details['student_id']; ?>' 
						class="btn btn-danger" title="Delete Student"> 
								<i class="icon icon-remove"></i>
							</a>

						<?php	if ($details['payed'] == 'paid'): ?>
								<a id="href_delete"href='/students/download?student_id=<?php echo $details['student_id']; ?>' 
								class="btn btn-success" title="download invoice"> 
									<i class="icon icon-download"></i>
								</a>
							<?php endif; ?>
						</td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php endif ?>
		</div>


		<div id="student-details" class="modal fade" role="dialog">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h4 class="modal-title">Student Details</h4>
		      </div>
		      <div class="modal-body">
		      	<h1> test </h1>

		        <dl>
		        	<dt>studentID</dt><dd id="studenID"></dd>
		        	<dt>First Name</dt><dd id="unang_pangalan"></dd>
		        	<dt>Last Name</dt><dd id="apilido"></dd>
		        </dl>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="icon icon-remove"></i></button>
		      </div>
		    </div>

		  </div>
		</div>

	</nav>
