	<link type="text/css" rel="stylesheet" href="../../../../css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="/css/mystyles.css" />
    
    <script src="/js/vendor/jquery-3.1.1.min.js"></script>
    <script src="/js/vendor/bootstrap.min.js"></script>
    <script src="/js/subjects.js"></script>

		<h1 align="center">Subject Records</h1>

<form>
	     <div id="container">


		<a style="float:left" href="/">(Return)</a>
		<a class="pull-right btn btn-success "  type="submit" href="/subjects/add"><i class="icon icon-plus"></i></a>

	<?php if (empty($this->subjects)): ?>
			<div class="alert alert-info">No subject yet</div>
	<?php else: ?>
	<table class="table table-bordered table-condensed table-striped">
			<tr>
				<th>id</th>
				<th>subject</th>
				<th>lecUnit</th>
				<th>labUnit</th>
				<th>subjectUnit</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>	
		<?php foreach ($this->subjects as $details):?>
	<tr>
		<td align="center" ><?php echo $details['subject_id']; ?></td>
		<td align="center"><?php echo $details['subject']; ?></td>
		<td	align="center"><?php echo $details['lec_unit']; ?></td>
		<td	align="center"><?php echo $details['lab_unit']; ?></td>
		<td	align="center"><?php echo $details['subject_unit']; ?></td>
		<td>	<a 
					onclick="viewDetails(<?php echo $details['subject_id']; ?>);" 
					class="btn" 
					title="edit Student"
					data-toggle="modal" data-target="#subject-details"
					> 
					<i class="icon icon-search"></i>
				</a></td>
		<td style="width: 1px; wrap: nowrap;"><?php echo "<a href='/subjects/edit?subject_id=". $details['subject_id']. "'>edit</a>"?></td>
		<td style="width: 1px; wrap: nowrap;"><?php echo "<a href='/subjects/delete?subject_id=". $details['subject_id']. "'>delete</a>"?></td>

	</tr>
	<?php endforeach;?>
	</table>
	<?php endif; ?>
	</div>

</form>


<div id="subject-details" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Student Details</h4>
      </div>
      <div class="modal-body">
      	<h1> test </h1>

        <dl>
        	<dt>subejectID</dt><dd id="subjectID"></dd>
        	<dt>subjectName</dt><dd id="subjectName"></dd>
        	<dt>subjectUnit</dt><dd id="subjectUnit"></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Sarado</button>
      </div>
    </div>

  </div>
</div>

</nav>
