
<script src="/js/subjects.js"></script>

	<h1 align="center">Subject Records</h1>


	<div id="container">
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">View Subjects</a>
		
				<form class="navbar-form pull-right">
				  	<a type="button" class="btn" href="/index">return</a>
				</form>
			</div>
		</div>
		<a  
			class="pull-right btn btn-success" 
			title="add Subject"
			data-toggle="modal" data-target="#subject-add"
			> 
			<i class="icon icon-plus"></i>
		</a>
		<a class="pull-right btn btn-success "  type="submit" href="/subjects/add"><i class="icon icon-plus"></i></a>

	<?php if (empty($this->subjects)): ?>
			<div class="alert alert-info">No subject yet</div>
	<?php else: ?>

<form>
	<div id="subjects-pagination" class="pagination">
		  <ul>
		    <li><a href="/subjects/index?page=<?php echo $this->currentPage <= 1?1:$this->currentPage-1; ?>">Prev</a></li>
		    <?php for ($pageNumber = 1; $pageNumber <= Subject::getNumberOfPages($this->subjectsCount); $pageNumber++) { ?>
		    	<li class="<?php echo ($pageNumber == $this->currentPage)?'active':'';?>"><a href="/subjects/index?page=<?php echo $pageNumber; ?>"><?php echo $pageNumber; ?></a></li>
		    <?php } ?>
		    <li><a href="/subjects/index?page=<?php echo ($this->currentPage >= Subject::getNumberOfPages($this->subjectsCount))?$this->currentPage:$this->currentPage+1; ?>">Next</a></li>
		  </ul>
	</div>
	<table class="table table-bordered table-condensed table-striped">
			<tr>
				<th>id</th>
				<th>subject</th>
				<th>lecUnit</th>
				<th>labUnit</th>
				<th>subjectUnit</th>
				<th>Details</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>	
		<?php foreach ($this->subjects as $details):?>
	<tr>
		<td align="center" ><?php echo $details['subject_id']; ?></td>
		<td align="center"><?php echo $details['subject']; ?></td>
		<td	align="center"><?php echo $details['lec_unit']; ?></td>
		<td	align="center"><?php echo $details['lab_unit']; ?></td>
		<td	align="center"><?php echo $details['subject_unit']; ?></td>
		<td>	
			<a 
				onclick="viewDetails(<?php echo $details['subject_id']; ?>);" 
				class="btn" 
				title="View Subject"
				data-toggle="modal" data-target="#subject-details"> 
				<i class="icon icon-search"></i>
			</a>
		</td>
		<td style="width: 1px; wrap: nowrap;">
		<!--	<a href="/subjects/edit?subject_id=<?php echo $details['subject_id']; ?>" 
				   class="btn" 
				   title="edit Subject"> 
				   <i class="icon icon-edit"></i>
			</a>-->
			<a 
				onclick="editSubject(<?php echo $details['subject_id']; ?>)" 
				class="btn" 
				title="edit Student"
				data-toggle="modal" data-target="#subject-edit"
				> 
				<i class="icon icon-edit"></i>
			</a>	
		</td>					
		<td style="width: 1px; wrap: nowrap;">			
			<a href='/subjects/delete?subject_id=<?php echo $details['subject_id']; ?>' 
						class="btn btn-danger" title="subject"> 
								<i class="icon icon-remove"></i>
							</a></td>

	</tr>
	<?php endforeach;?>
	</table>
	<?php endif; ?>
	</div>

</form>


<div id="subject-details" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Subject Details</h4>
      </div>
      <div class="modal-body">
        <dl>
        	<dt>subejectID</dt><dd id="subjectID"></dd>
        	<dt>subjectName</dt><dd id="subjectName"></dd>
        	<dt>subjectUnit</dt><dd id="subjectUnit"></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal"><i class="icon icon-remove"></i></button>
      </div>
    </div>

  </div>
</div>
<div id="subject-edit" class="modal fade" role="dialog">

	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title">Subject Edit</h4>
	      </div>
	      <div class="modal-body">
	      	<h1> Subject Edit </h1>

	        <dl>
	        	<dt>subjectID</dt><dd id="editSubjectID"></dd>
	        	<dt>Subject</dt><dd><input type="text" id="editSubjectName" /></dd>
	        	<dt>Subject Lec</dt><dd><input type="text" id="editSubjectLec" /></dd>
	        	<dt>Subject Lab</dt><dd><input type="text" id="editSubjectLab" /></dd>
	        	<dt>Subject Unit </dt><dd><input type="text" id="editSubjectUnit" /></dd>
	        	<dt>Semester Number </dt><dd><input type="text" id="editSemesterNumber" /></dd>
	        </dl>
	      </div>
	      <div class="modal-footer">
	      	<button data-dismiss="modal" class="btn btn-default" id="button_save" type="submit" name="edit" value="save" onclick="updateSubject()">save</button>
	        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="icon icon-remove"></i></button>
	      </div>
	    </div>

	  </div>	
</div>
<div id="subject-add" class="modal fade" role="dialog">

	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title">Subject Edit</h4>
	      </div>
	      <div class="modal-body">
	      	<h1> Subject Edit </h1>

	        <dl>
	        	<dt>subjectID</dt><dd id="addSubjectID"></dd>
	        	<dt>Subject</dt><dd><input type="text" id="addSubjectName" /></dd>
	        	<dt>Subject Lec</dt><dd><input type="text" id="addSubjectLec" /></dd>
	        	<dt>Subject Lab</dt><dd><input type="text" id="addSubjectLab" /></dd>
	        	<dt>Subject Unit </dt><dd><input type="text" id="addSubjectUnit" /></dd>
	        	<dt>Subject Number </dt><dd><input type="text" id="addSubjectNumber" /></dd>
	        </dl>
	      </div>
	      <div class="modal-footer">
	      	<button data-dismiss="modal" class="btn btn-default" id="button_save" type="submit" name="edit" value="save" onclick="addSubject()">save</button>
	        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">	<i class="icon icon-remove"></i></button>
	      </div>
	    </div>

	  </div>	
</div>
</nav>
