
<script src="/js/subjects.js"></script>

	<h1 align="center">Subject Records</h1>


	<div id="container">
		<div class="navbar">
			<div class="navbar-inner">
				<a class="brand" href="#">View Subjects</a>
		
				<form class="navbar-form pull-right">
				  	<a type="button" class="btn" href="/index">return</a>
				</form>
			</div>
		</div>
		<a class="pull-right btn btn-success "  type="submit" href="/subjects/add"><i class="icon icon-plus"></i></a>

	<?php if (empty($this->subjects)): ?>
			<div class="alert alert-info">No subject yet</div>
	<?php else: ?>
<form>
	<table class="table table-bordered table-condensed table-striped">
			<tr>
				<th>id</th>
				<th>subject</th>
				<th>lecUnit</th>
				<th>labUnit</th>
				<th>subjectUnit</th>
				<th>Details</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>	
		<?php foreach ($this->subjects as $details):?>
	<tr>
		<td align="center" ><?php echo $details['subject_id']; ?></td>
		<td align="center"><?php echo $details['subject']; ?></td>
		<td	align="center"><?php echo $details['lec_unit']; ?></td>
		<td	align="center"><?php echo $details['lab_unit']; ?></td>
		<td	align="center"><?php echo $details['subject_unit']; ?></td>
		<td>	
			<a 
				onclick="viewDetails(<?php echo $details['subject_id']; ?>);" 
				class="btn" 
				title="View Subject"
				data-toggle="modal" data-target="#subject-details"> 
				<i class="icon icon-search"></i>
			</a>
		</td>
		<td style="width: 1px; wrap: nowrap;">
			<a href="/subjects/edit?subject_id=<?php echo $details['subject_id']; ?>" 
				   class="btn" 
				   title="edit Subject"> 
				   <i class="icon icon-edit"></i>
			</a>
		</td>					
		<td style="width: 1px; wrap: nowrap;">			
			<a href='/subjects/delete?subject_id=<?php echo $details['subject_id']; ?>' 
						class="btn btn-danger" title="subject"> 
								<i class="icon icon-remove"></i>
							</a></td>

	</tr>
	<?php endforeach;?>
	</table>
	<?php endif; ?>
	</div>

</form>


<div id="subject-details" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Subject Details</h4>
      </div>
      <div class="modal-body">
        <dl>
        	<dt>subejectID</dt><dd id="subjectID"></dd>
        	<dt>subjectName</dt><dd id="subjectName"></dd>
        	<dt>subjectUnit</dt><dd id="subjectUnit"></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal"><i class="icon icon-remove"></i></button>
      </div>
    </div>

  </div>
</div>

</nav>
