
<form  method ="POST">
<nav id ="searchStudent">
	<div id="container"> 
		<h1>Add User</h1>

		<h3 id="input"></h3>
		<input id="date_start" data-date-format="yyyy-mm-dd" type="text" name="username" "  /> User Name<br/>
		<input id="date_end" data-date-format="yyyy-mm-dd" type="text" name="password" "  /> Password<br/>
		
		<input class="btn" id="button_save" type="submit" name="save" value="save" />		
		<a style="float:right" href="/Admin">(Return)</a>
	</div>
</nav>	
</form>


