

  <script src="/js/admin.js"></script>

<nav id ="searchStudent">
	<div id="container">
	<form>
		<a style="float:left" href="/index">(Return)</a>
	</form>
		<table class="table table-bordered table-condensed table-striped">
			<a class="pull-right btn btn-success" 
			href="/Admin/add">
			<i class="icon-plus"></i></a>
			<tr>
				<th>User_id</th>
				<th>User Name</th>
				<th>Password</th>
				<th>Details</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
				<?php foreach ($this->admin as $details):?>
				<tr>
				<td align="center"><?php echo $details['user_id']; ?></td>
				<td align="center"><?php echo $details['username']; ?></td>
				<td align="center"><?php echo $details['password']; ?></td>
				<td>	
					<a 
						onclick="viewDetails(<?php echo $details['user_id']; ?>);" 
						class="btn" 
						title="edit Student"
						data-toggle="modal" data-target="#admin-details"> 
						<i class="icon icon-search"></i>
					</a>
				</td>
				<td style="width: 1px; wrap: nowrap;">
					<a href="/Admin/edit?user_id=<?php echo $details['user_id']; ?>" 
				   		class="btn" 
				   		title="edit Admin"> 
				   		<i class="icon icon-edit"></i>
					</a>
				</td>					
				<td style="width: 1px; wrap: nowrap;">			
					<a href='/Admin/delete?user_id=<?php echo $details['user_id']; ?>' 
						class="btn btn-danger" title="Admin"> 
						<i class="icon icon-remove"></i>
					</a>
				</td>

				</tr>
			<?php endforeach;?>
		</table>	
	</div>


<div id="admin-details" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Admin Details</h4>
      </div>
      <div class="modal-body">
        <dl>
        	<dt>AdminID</dt><dd id="adminID"></dd>
        	<dt>Admin User Name</dt><dd id="adminUser"></dd>
        	<dt>Admin Password</dt><dd id="adminPass"></dd>
        </dl>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-danger" data-dismiss="modal"><i class="icon icon-remove"></i></button>
      </div>
    </div>

  </div>
</div>

</nav>

	

